/* eslint-disable no-console */

import calculateMaxWin from '@libs/services/soccer/calculateMaxWin';

const data = [
  {
    date: '2001-01-04',
    homeTeam: 'Kenya',
    awayTeam: 'Zambia',
    homeScore: 2,
    awayScore: 1,
    tournament: 'Friendly',
    city: 'Nairobi',
    country: 'Kenya',
  },
  {
    date: '2001-01-06',
    homeTeam: 'Costa Rica',
    awayTeam: 'Guatemala',
    homeScore: 5,
    awayScore: 2,
    tournament: 'FIFA World Cup qualification',
    city: 'Miami',
    country: 'United States',
  },
  {
    date: '2001-01-06',
    homeTeam: 'Egypt',
    awayTeam: 'United Arab Emirates',
    homeScore: 2,
    awayScore: 1,
    tournament: 'Friendly',
    city: 'Cairo',
    country: 'Egypt',
  },
  {
    date: '2001-01-06',
    homeTeam: 'Eswatini',
    awayTeam: 'Angola',
    homeScore: 1,
    awayScore: 0,
    tournament: 'Friendly',
    city: 'Manzini',
    country: 'Eswatini',
  },
  {
    date: '2001-01-07',
    homeTeam: 'Angola',
    awayTeam: 'Lesotho',
    homeScore: 2,
    awayScore: 0,
    tournament: 'Friendly',
    city: 'Manzini',
    country: 'Eswatini',
  },
  {
    date: '2001-01-07',
    homeTeam: 'Eswatini',
    awayTeam: 'Namibia',
    homeScore: 2,
    awayScore: 1,
    tournament: 'Friendly',
    city: 'Manzini',
    country: 'Eswatini',
  },
  {
    date: '2001-01-07',
    homeTeam: 'Togo',
    awayTeam: 'Burkina Faso',
    homeScore: 1,
    awayScore: 1,
    tournament: 'Friendly',
    city: 'Lomé',
    country: 'Togo',
  },
  {
    date: '2001-01-09',
    homeTeam: 'Egypt',
    awayTeam: 'Zambia',
    homeScore: 3,
    awayScore: 1,
    tournament: 'Friendly',
    city: 'Cairo',
    country: 'Egypt',
  },
  {
    date: '2001-01-09',
    homeTeam: 'Eswatini',
    awayTeam: 'Lesotho',
    homeScore: 2,
    awayScore: 2,
    tournament: 'Friendly',
    city: 'Manzini',
    country: 'Eswatini',
  },
  {
    date: '2001-01-11',
    homeTeam: 'Romania',
    awayTeam: 'Jordan',
    homeScore: 0,
    awayScore: 1,
    tournament: 'Millennium Cup',
    city: 'Margao',
    country: 'India',
  },
  {
    date: '2001-01-12',
    homeTeam: 'Algeria',
    awayTeam: 'Burundi',
    homeScore: 2,
    awayScore: 1,
    tournament: 'African Cup of Nations qualification',
    city: 'Algiers',
    country: 'Algeria',
  },
  {
    date: '2001-01-12',
    homeTeam: 'Bosnia and Herzegovina',
    awayTeam: 'Bangladesh',
    homeScore: 2,
    awayScore: 0,
    tournament: 'Millennium Cup',
    city: 'Cochin',
    country: 'India',
  },
  {
    date: '2001-01-12',
    homeTeam: 'Qatar',
    awayTeam: 'Kuwait',
    homeScore: 1,
    awayScore: 0,
    tournament: 'Friendly',
    city: 'Doha',
    country: 'Qatar',
  },
  {
    date: '2001-01-12',
    homeTeam: 'Uzbekistan',
    awayTeam: 'Bahrain',
    homeScore: 5,
    awayScore: 0,
    tournament: 'Millennium Cup',
    city: 'Calcutta',
    country: 'India',
  },
  {
    date: '2001-01-13',
    homeTeam: 'Burkina Faso',
    awayTeam: 'Angola',
    homeScore: 1,
    awayScore: 0,
    tournament: 'African Cup of Nations qualification',
    city: 'Ouagadougou',
    country: 'Burkina Faso',
  },
  {
    date: '2001-01-13',
    homeTeam: 'India',
    awayTeam: 'Iceland',
    homeScore: 0,
    awayScore: 3,
    tournament: 'Millennium Cup',
    city: 'Cochin',
    country: 'India',
  },
  {
    date: '2001-01-13',
    homeTeam: 'Kenya',
    awayTeam: 'Gabon',
    homeScore: 2,
    awayScore: 1,
    tournament: 'African Cup of Nations qualification',
    city: 'Nairobi',
    country: 'Kenya',
  },
  {
    date: '2001-01-13',
    homeTeam: 'Namibia',
    awayTeam: 'Madagascar',
    homeScore: 2,
    awayScore: 2,
    tournament: 'African Cup of Nations qualification',
    city: 'Windhoek',
    country: 'Namibia',
  },
  {
    date: '2001-01-13',
    homeTeam: 'Nigeria',
    awayTeam: 'Zambia',
    homeScore: 1,
    awayScore: 0,
    tournament: 'African Cup of Nations qualification',
    city: 'Lagos',
    country: 'Nigeria',
  },
  {
    date: '2001-01-13',
    homeTeam: 'Tunisia',
    awayTeam: 'Morocco',
    homeScore: 0,
    awayScore: 1,
    tournament: 'African Cup of Nations qualification',
    city: 'Tunis',
    country: 'Tunisia',
  },
  {
    date: '2001-01-13',
    homeTeam: 'Uganda',
    awayTeam: 'Senegal',
    homeScore: 1,
    awayScore: 1,
    tournament: 'African Cup of Nations qualification',
    city: 'Kampala',
    country: 'Uganda',
  },
  {
    date: '2001-01-14',
    homeTeam: 'DR Congo',
    awayTeam: 'Ghana',
    homeScore: 2,
    awayScore: 1,
    tournament: 'African Cup of Nations qualification',
    city: 'Kinshasa',
    country: 'DR Congo',
  },
  {
    date: '2001-01-14',
    homeTeam: 'Egypt',
    awayTeam: 'Libya',
    homeScore: 4,
    awayScore: 0,
    tournament: 'African Cup of Nations qualification',
    city: 'Cairo',
    country: 'Egypt',
  },
  {
    date: '2001-01-14',
    homeTeam: 'Guinea',
    awayTeam: 'Togo',
    homeScore: 0,
    awayScore: 0,
    tournament: 'African Cup of Nations qualification',
    city: 'Conakry',
    country: 'Guinea',
  },
  {
    date: '2001-01-14',
    homeTeam: 'Liberia',
    awayTeam: 'Congo',
    homeScore: 5,
    awayScore: 1,
    tournament: 'African Cup of Nations qualification',
    city: 'Monrovia',
    country: 'Liberia',
  },
  {
    date: '2001-01-14',
    homeTeam: 'Romania',
    awayTeam: 'Hong Kong',
    homeScore: 4,
    awayScore: 2,
    tournament: 'Millennium Cup',
    city: 'Margao',
    country: 'India',
  },
  {
    date: '2001-01-14',
    homeTeam: 'Serbia',
    awayTeam: 'Bosnia and Herzegovina',
    homeScore: 1,
    awayScore: 1,
    tournament: 'Millennium Cup',
    city: 'Cochin',
    country: 'India',
  },
  {
    date: '2001-01-14',
    homeTeam: 'Zimbabwe',
    awayTeam: 'Lesotho',
    homeScore: 1,
    awayScore: 2,
    tournament: 'African Cup of Nations qualification',
    city: 'Bulawayo',
    country: 'Zimbabwe',
  },
  {
    date: '2001-01-15',
    homeTeam: 'Chile',
    awayTeam: 'Bahrain',
    homeScore: 2,
    awayScore: 0,
    tournament: 'Millennium Cup',
    city: 'Calcutta',
    country: 'India',
  },
  {
    date: '2001-01-16',
    homeTeam: 'Bangladesh',
    awayTeam: 'Serbia',
    homeScore: 1,
    awayScore: 4,
    tournament: 'Millennium Cup',
    city: 'Cochin',
    country: 'India',
  },
  {
    date: '2001-01-16',
    homeTeam: 'Hong Kong',
    awayTeam: 'Jordan',
    homeScore: 0,
    awayScore: 2,
    tournament: 'Millennium Cup',
    city: 'Margao',
    country: 'India',
  },
  {
    date: '2001-01-17',
    homeTeam: 'Chile',
    awayTeam: 'Uzbekistan',
    homeScore: 2,
    awayScore: 0,
    tournament: 'Millennium Cup',
    city: 'Calcutta',
    country: 'India',
  },
  {
    date: '2001-01-17',
    homeTeam: 'China PR',
    awayTeam: 'Egypt',
    homeScore: 0,
    awayScore: 0,
    tournament: 'Friendly',
    city: 'Teheran',
    country: 'Iran',
  },
  {
    date: '2001-01-17',
    homeTeam: 'Israel',
    awayTeam: 'Uzbekistan',
    homeScore: 2,
    awayScore: 0,
    tournament: 'Friendly',
    city: "Beit She'an",
    country: 'Israel',
  },
  {
    date: '2001-01-17',
    homeTeam: 'Kuwait',
    awayTeam: 'Syria',
    homeScore: 2,
    awayScore: 0,
    tournament: 'Friendly',
    city: 'Doha',
    country: 'Qatar',
  },
  {
    date: '2001-01-19',
    homeTeam: 'Iran',
    awayTeam: 'China PR',
    homeScore: 4,
    awayScore: 0,
    tournament: 'Friendly',
    city: 'Teheran',
    country: 'Iran',
  },
  {
    date: '2001-01-20',
    homeTeam: 'Chile',
    awayTeam: 'Iceland',
    homeScore: 2,
    awayScore: 0,
    tournament: 'Millennium Cup',
    city: 'Calcutta',
    country: 'India',
  },
  {
    date: '2001-01-20',
    homeTeam: 'Ivory Coast',
    awayTeam: 'Sudan',
    homeScore: 2,
    awayScore: 0,
    tournament: 'African Cup of Nations qualification',
    city: 'Bouaké',
    country: 'Ivory Coast',
  },
  {
    date: '2001-01-20',
    homeTeam: 'Mali',
    awayTeam: 'Guinea',
    homeScore: 0,
    awayScore: 1,
    tournament: 'Friendly',
    city: 'Bamako',
    country: 'Mali',
  },
  {
    date: '2001-01-20',
    homeTeam: 'Serbia',
    awayTeam: 'Romania',
    homeScore: 2,
    awayScore: 0,
    tournament: 'Millennium Cup',
    city: 'Margao',
    country: 'India',
  },
  {
    date: '2001-01-22',
    homeTeam: 'Bosnia and Herzegovina',
    awayTeam: 'Chile',
    homeScore: 1,
    awayScore: 0,
    tournament: 'Millennium Cup',
    city: 'Calcutta',
    country: 'India',
  },
  {
    date: '2001-01-23',
    homeTeam: 'Burkina Faso',
    awayTeam: 'Mali',
    homeScore: 0,
    awayScore: 2,
    tournament: 'Friendly',
    city: 'Ouagadougou',
    country: 'Burkina Faso',
  },
  {
    date: '2001-01-23',
    homeTeam: 'Egypt',
    awayTeam: 'North Korea',
    homeScore: 1,
    awayScore: 0,
    tournament: 'Friendly',
    city: 'Ismailia',
    country: 'Egypt',
  },
  {
    date: '2001-01-23',
    homeTeam: 'Serbia',
    awayTeam: 'Japan',
    homeScore: 1,
    awayScore: 0,
    tournament: 'Millennium Cup',
    city: 'Calcutta',
    country: 'India',
  },
  {
    date: '2001-01-23',
    homeTeam: 'Thailand',
    awayTeam: 'Kuwait',
    homeScore: 5,
    awayScore: 4,
    tournament: 'Friendly',
    city: 'Bangkok',
    country: 'Thailand',
  },
  {
    date: '2001-01-24',
    homeTeam: 'South Korea',
    awayTeam: 'Norway',
    homeScore: 2,
    awayScore: 3,
    tournament: 'Lunar New Year Cup',
    city: 'So Kon Po',
    country: 'Hong Kong',
  },
  {
    date: '2001-01-24',
    homeTeam: 'Mexico',
    awayTeam: 'Bulgaria',
    homeScore: 0,
    awayScore: 2,
    tournament: 'Friendly',
    city: 'Morelia',
    country: 'Mexico',
  },
  {
    date: '2001-01-25',
    homeTeam: 'Benin',
    awayTeam: 'Cameroon',
    homeScore: 1,
    awayScore: 3,
    tournament: 'Friendly',
    city: 'Cotonou',
    country: 'Benin',
  },
  {
    date: '2001-01-25',
    homeTeam: 'Bosnia and Herzegovina',
    awayTeam: 'Serbia',
    homeScore: 0,
    awayScore: 2,
    tournament: 'Millennium Cup',
    city: 'Calcutta',
    country: 'India',
  },
  {
    date: '2001-01-26',
    homeTeam: 'Algeria',
    awayTeam: 'Namibia',
    homeScore: 1,
    awayScore: 0,
    tournament: 'FIFA World Cup qualification',
    city: 'Algiers',
    country: 'Algeria',
  },
  {
    date: '2001-01-27',
    homeTeam: 'Botswana',
    awayTeam: 'Eswatini',
    homeScore: 1,
    awayScore: 2,
    tournament: 'Friendly',
    city: 'Gaborone',
    country: 'Botswana',
  },
  {
    date: '2001-01-27',
    homeTeam: 'Grenada',
    awayTeam: 'Trinidad and Tobago',
    homeScore: 1,
    awayScore: 2,
    tournament: 'Friendly',
    city: "St. George's",
    country: 'Grenada',
  },
  {
    date: '2001-01-27',
    homeTeam: 'South Korea',
    awayTeam: 'Paraguay',
    homeScore: 1,
    awayScore: 1,
    tournament: 'Lunar New Year Cup',
    city: 'So Kon Po',
    country: 'Hong Kong',
  },
  {
    date: '2001-01-27',
    homeTeam: 'Nigeria',
    awayTeam: 'Sudan',
    homeScore: 3,
    awayScore: 0,
    tournament: 'FIFA World Cup qualification',
    city: 'Port Harcourt',
    country: 'Nigeria',
  },
];

describe('1', () => {
  test('2', () => {
    console.log(calculateMaxWin(data));
  });
});
